### ISSUE TITLE
tokenize problem

### ISSUE THREAD

**Issue by ErwinLiYH** [epfml/X2Static#2]
Hello, your project is really helpful for me, but I am confused about how this model embeds words like "lemongrass" which will be tokenized as [lemon. ##grass] in Bert. Could you please illustrate it :)

**Comment by guptaprkhr** [comment]
Hi, 
This model learns static word embeddings in the end and if lemongrass is in the vocab(which it should for the trained models) it'll return the static emedding for it. The BERT tokenization is only used for training these static embeddings.
